### ISSUE TITLE
Don't bundle with Amecs API

### ISSUE THREAD

**Issue by NebelNidas** [Siphalor/nmuk#8]
Is there a specific reason as to why Nmuk is bundled with Amecs API? I understand why it's bundled with the user-facing Amecs (non-API), but as a developer, I'd like to only get the libraries imported I'm declaring myself.

Edit: How does the current system even work? Aren't you creating a circular dependency via these two lines?
- [Amecs API depending on Nmuk](https://github.com/Siphalor/amecs-api/blob/d7012472fc6d0c87e85c8583ffac6b580e56a2eb/build.gradle#L34=)
- [Nmuk depending on Amecs API](https://github.com/Siphalor/nmuk/blob/0d124f634d00778d0330be3e601619385b6e7154/build.gradle#L38=)

**Comment by Klotzi111** [comment]
There is no circular dependency. As you can see in the lines linked by you (the lines below) there is an `exclude module: "amecsapi-${project.minecraft_major_version}"` and also the other way round. This mean that the `amecsapi` artefact is ignored when including `nmuk`.
Also the other mod artefacts are not "bundles" as you described it. Bundeling would mean that the final mod jar would include the other mod jars (artefacts). But this is not the case. These artefacts are only included with `modImplementation` so that we can use the classes and methods of these artefacts when compiling.
So if you want to only have `nmuk` or `amecsapi` on you classpath/compilepath then also add these `exclude` rules.
